quasiforum/Pages/Items/Edit.cshtml.cs
using quasiforum.Models;
using quasiforum.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;

namespace quasiforum.Pages.Items
{
    public class EditModel : PageModel
    {
        private IForumRepository _repository;
        private UserManager<AppUser> _userManager;

        [BindProperty]
        public IFormFile Image { get; set; }
       
        [BindProperty]
        public int TopicId { get; set; }
        private Topic _topic { get; set; }

        [BindProperty]
        public Post post { get; set; }

        public EditModel(IForumRepository repository, UserManager<AppUser> userManager)
        {
            _repository = repository;
            _userManager = userManager;
        }
        public IActionResult OnGet(int id)
        {
            var currentUser = _userManager.GetUserId(User);
 
            if (id > 0)
            {
                post = _repository.GetPostDetails(id);
                TopicId = post.TopicId;
                _topic = _repository.GetTopicDetails(TopicId);
            }
            else // creating new instance
                
                post = new Post();

            return Page();
        }

        public IActionResult OnGetCreateItem(int id)
        {
            TopicId = id;
            _topic = _repository.GetTopicDetails(TopicId);
            //ItemOptions = _collection.GetItemOptions(_collection);
            post = new Post();
            //itemFields = item.GetOptionsValues(item);
            return Page();
        }
        public IActionResult OnPostDelete()
        {
            _repository.DeleteItem(post.id);

            return RedirectToPage("Collections");
        }

        public IActionResult OnPost()
        {
            _topic = _repository.GetTopicDetails(TopicId);

            if (ModelState.IsValid)
            {
                post.OwnerId = _userManager.GetUserId(User);
                if (post.id > 0) // edit
                {
                    post.TopicId = TopicId;
                    post = _repository.Update(post);
                }
                else // create
                {
                    post.TopicId = TopicId;
                    post.ParentTopic = _topic;
                    post.CreationDate = DateTime.Now;
                    post = _repository.Add(post);
                }

                return RedirectToPage("/Collections/CollectionDetails", new { id = TopicId });
            }
            return Page();
        }
    }
}

quasiforum/Pages/UserProfile/UserProfile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using quasiforum.Models;
using quasiforum.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace quasiforum.Pages.UserProfile
{
    public class UserProfileModel : PageModel
    {
        private readonly IForumRepository _ForumRepository;
        private readonly UserManager<AppUser> _userManager;
        [BindProperty]
        public AppUser thisUser { get; set; }
        [BindProperty]
        public IFormFile Image { get; set; }
        public IEnumerable<Post> PostsList { get; set; }
        [BindProperty]
        public IEnumerable<Topic> TopicsList { get; set; }
        public Topic currentTopic { get; set; }
        public int count { get; set; }
        public bool isDarkTheme { get; set; }
        //public int colId { get; set; }

        public UserProfileModel(IForumRepository forumRepository, UserManager<AppUser> userManager)
        {
            _ForumRepository = forumRepository;
            _userManager = userManager;
        }
        public async Task<IActionResult> OnGet()
        {
            thisUser = await _userManager.GetUserAsync(User);

            if (thisUser == null)
            {
                return Redirect("/Index");
            }

            TopicsList = _ForumRepository.GetMyTopics(thisUser.Id);
            return Page();
        }

        public int GetItemsCount(Topic topic)
        {
            return _ForumRepository.GetAllTopicPosts(topic.id).Count();
        }
        
        public IActionResult OnPostDelete(int topicId)
        {
            _ForumRepository.DeleteTopic(topicId);

            return RedirectToPage("/UserProfile/UserProfile");
        }
        public async Task<IActionResult> OnPostUpdateUser(bool isDarkTheme, bool Language)
        {
            thisUser = await _userManager.GetUserAsync(User);

            if (Image != null)
            {
                var response = ImageUploader.UploadImage(Image);
                if (response.StatusCode == 200) // OK
                {
                    thisUser.AvatarImagePath = response.URL;
                }
            }
            thisUser.isDarkTheme = isDarkTheme;
            thisUser.Language = Language;
            
            await _userManager.UpdateAsync(thisUser);
            return RedirectToPage("/UserProfile/UserProfile");
        }
    }
}

quasiforum/Pages/UserProfile/UserProfile.cshtml
@page
@model quasiforum.Pages.UserProfile.UserProfileModel


@{
    ViewData["Title"] = @Locale.Translations["Profile"];
    AppUser user = await UserManager.GetUserAsync(User);
    user.SetLocale();
}
<script>
        $(document).ready(function () {
            $(".btnPost").click(function () {
                $(this).html(
                    '<i class="fa fa-circle-o-notch fa-spin"></i> @Locale.Translations["Loading"]...'
                );
            });
        });
</script>
<section class="py-5">
    <input type="hidden" asp-for="User" />
    <div class="row align-items-center">
        <div class="col-md-4"><img class="card-img-top mb-5 mb-md-0 rounded-1 img-fluid" src="@user.AvatarImagePath" alt="title_image" /></div>
        <div class="col-md-8">
            <h1 class="display-5 fw-bolder">@Model.thisUser.UserName</h1>
            <div class="form-group">
                <form method="post" enctype="multipart/form-data">
                    <h4>@Locale.Translations["Personalize:"]</h4>
                    <div class="card mb-2">
                        <div class="card-header">
                            @Locale.Translations["Select image (drag and drop supported):"]
                        </div>
                        <div class="card-body">
                            <div class="custom-file">
                                <input asp-for="Image" class="custom-file-input form-control text-center" />
                            </div>
                        </div>
                    </div>

                    <div class="card mb-2">
                        <div class="card-header">@Locale.Translations["Language:"]</div>
                        <div class="card-body">
                            <div class="d-inline-block me-1">EN</div>
                            <div class="form-check form-switch d-inline-block">
                                <input class="form-check-input" type="checkbox" name="Language" checked="@Model.thisUser.Language" value="true" />
                                <label class="form-check-label">RU</label>
                            </div>
                        </div>
                    </div>

                    <div class="card mb-2">
                        <div class="card-header">@Locale.Translations["Theme:"]</div>
                        <div class="card-body">
                            <div class="d-inline-block me-1">@Locale.Translations["LIGHT"]</div>
                            <div class="form-check form-switch d-inline-block">
                                <input class="form-check-input" type="checkbox" name="isDarkTheme" checked="@Model.thisUser.isDarkTheme" value="true" />
                                <label class="form-check-label">@Locale.Translations["DARK"]</label>
                            </div>
                        </div>
                    </div>
                    <button type="submit" asp-page-handler="UpdateUser" class="btn btnPost btn-sm btn-outline-danger"><i class="fa fa-check-square-o" aria-hidden="true"></i> @Locale.Translations["Apply"]</button>
                </form>
            </div>
        </div>
    </div>
</section>

<section class="py-5">
    <a asp-page="/Collections/Edit" asp-route-Id="" class="btn btnPost btn-info btn-sm mb-3"><i class="fa fa-plus" aria-hidden="true"></i> @Locale.Translations["Create new topic"]</a>
    <div class="row align-items-center">
        @if (Model.TopicsList.Count() > 0)
        {
            <script src="~/js/dataTable.js"></script>
            <h1>@Locale.Translations["My Topics"]:</h1>

            <table id="dataTable" class="table align-middle mb-0" style="width:100%">
                <thead>
                    <tr>
                        <th>@Locale.Translations["Name"]</th>
                        <th>@Locale.Translations["Created"]</th>
                        <th>@Locale.Translations["Posts Count"]</th>
                        <th>@Locale.Translations["Actions"]</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model.TopicsList)
                    {
                        <tr>
                            <td>
                                <div class="d-flex align-items-center">
                                    <img src="@item.imagePath"
                                         alt=""
                                         style="width: 45px; height: 45px"
                                         class="rounded-circle" />
                                    <div class="ms-3">
                                        <p class="fw-bold mb-1">@item.Name</p>
                                    </div>
                                </div>
                            </td>
                          
                            <td>
                                <p class="fw-normal mb-1">@item.CreationDate.ToShortDateString()</p>
                            </td>
                            <td>
                                <span class="fw-normal mb-1">@Model.GetItemsCount(item)</span>
                            </td>
                            <td>
                                @*<div class="dropdown">
                                    <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown">
                                        Action
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-right text-center">*@
                                <a asp-page="/Collections/CollectionDetails" asp-route-Id="@item.id" class="btn btnPost btn-outline-warning btn-sm">
                                    <i class="fa fa-eye" aria-hidden="true"></i>
                                    @Locale.Translations["View"]
                                </a>
                                <a asp-page="/Collections/Edit" asp-route-Id="@item.id" class="btn btnPost btn-outline-info btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> @Locale.Translations["Edit"]</a>
                                <a asp-page="/Items/Edit" asp-route-Id="@item.id" asp-page-handler="CreateItem" class="btn btnPost btn-outline-success btn-sm"><i class="fa fa-plus" aria-hidden="true"></i> @Locale.Translations["Add post"]</a>
                                <button type="button" class="btn btn-outline-danger btn-sm dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-trash-o" aria-hidden="true"></i> @Locale.Translations["Delete"]
                                </button>
                                <div class="dropdown-menu dropdown-menu-right text-center">
                                    <div class="dropdown-header" style="color:red">@Locale.Translations["Confirm delete"]</div>
                                    <form method="post">
                                        <button type="button" class="btn btn-sm btn-success" data-toggle="dropdown"><i class="fa fa-window-close" aria-hidden="true"></i> @Locale.Translations["NO"]</button>
                                        <input type="hidden" name="topicId" value="@item.id" />
                                        <button type="submit" asp-page-handler="Delete" class="btn btn-sm btn-danger"><i class="fa fa-check-square" aria-hidden="true"></i> @Locale.Translations["YES"]</button>
                                    </form>
                                </div>
                                @*</div>
                                    </div>*@
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

        }
    </div>
</section>